/// Account balance type.
#[derive(Debug)]
pub enum AccountNormalBalanceType {
    /// Credit
    CREDIT,
    /// Debit
    DEBIT,
}

impl AccountNormalBalanceType {
    pub fn to_string(&self) -> String {
        match self {
            AccountNormalBalanceType::CREDIT => "CREDIT".to_string(),
            AccountNormalBalanceType::DEBIT => "DEBIT".to_string()
        }
    }
}

/// Subtypes of accounts, as used in the Chart of Accounts.
#[derive(Debug)]
pub enum AccountSubtypeValue {
    CASH_AND_BANK,
    COST_OF_GOODS_SOLD,
    CREDIT_CARD,
    CUSTOMER_PREPAYMENTS_AND_CREDITS,
    DEPRECIATION_AND_AMORTIZATION,
    DISCOUNTS,
    DUE_FOR_PAYROLL,
    DUE_TO_YOU_AND_OTHER_OWNERS,
    EXPENSE,
    GAIN_ON_FOREIGN_EXCHANGE,
    INCOME,
    INVENTORY,
    LOANS,
    LOSS_ON_FOREIGN_EXCHANGE,
    MONEY_IN_TRANSIT,
    NON_RETAINED_EARNINGS,
    OTHER_CURRENT_ASSETS,
    OTHER_CURRENT_LIABILITY,
    OTHER_INCOME,
    OTHER_LONG_TERM_ASSETS,
    OTHER_LONG_TERM_LIABILITY,
    PAYABLE,
    PAYABLE_BILLS,
    PAYABLE_OTHER,
    PAYMENT_PROCESSING_FEES,
    PAYROLL_EXPENSES,
    PROPERTY_PLANT_EQUIPMENT,
    RECEIVABLE,
    RECEIVABLE_INVOICES,
    RECEIVABLE_OTHER,
    RETAINED_EARNINGS,
    SALES_TAX,
    SYSTEM_CUSTOMER_CREDITS,
    TRANSFERS,
    UNCATEGORIZED_EXPENSE,
    UNCATEGORIZED_INCOME,
    UNKNOWN_ACCOUNT,
    VENDOR_PREPAYMENTS_AND_CREDITS,
}




/// Types of accounts, as used in the Chart of Accounts.
#[derive(Debug)]
pub enum AccountTypeValue {
    ASSET,
    EQUITY,
    EXPENSE,
    INCOME,
    LIABILITY,
}

/// Balance type that expresses how to change an account.
#[derive(Debug)]
pub enum BalanceType {
    CREDIT,
    DEBIT,
    /// Decrease using the inverse of the account's normal balance type. For contra accounts whose subtype is `DISCOUNTS` or `DEPRECIATION_AND_AMORTIZATION`, apply the amount in the account's normal balance type.
    DECREASE,
    /// Increase using the account's normal balance type. For contra accounts whose subtype is `DISCOUNTS` or `DEPRECIATION_AND_AMORTIZATION`, apply the amount in the inverse of the account's normal balance type.
    INCREASE,
}

/// Granular area of focus of a business.
#[derive(Debug)]
pub enum BusinessSubtypeValue {
    ADVERTISING_PUBLIC_RELATIONS,
    AGRICULTURE_RANCHING_FARMING,
    ARTISTS_PHOTOGRAPHERS_CREATIVE__ACTOR,
    ARTISTS_PHOTOGRAPHERS_CREATIVE__AUDIO_VISUAL_PRODUCTION,
    ARTISTS_PHOTOGRAPHERS_CREATIVE__CRAFTSPERSON,
    ARTISTS_PHOTOGRAPHERS_CREATIVE__DANCER_CHOREOG,
    ARTISTS_PHOTOGRAPHERS_CREATIVE__MUSICIAN,
    ARTISTS_PHOTOGRAPHERS_CREATIVE__OTHER,
    ARTISTS_PHOTOGRAPHERS_CREATIVE__PERFORMING_ARTS_ACTING_MUSIC_DANCE,
    ARTISTS_PHOTOGRAPHERS_CREATIVE__PHOTOGRAPHER,
    ARTISTS_PHOTOGRAPHERS_CREATIVE__VISUAL_ARTIST,
    AUTOMOTIVE_SALES_AND_REPAIR,
    CHURCH_RELIGIOUS_ORGANIZATION,
    CONSTRUCTION_HOME_IMPROVEMENT__CONTRACTOR,
    CONSTRUCTION_HOME_IMPROVEMENT__ENGINEER,
    CONSTRUCTION_HOME_IMPROVEMENT__HOME_INSPECTOR,
    CONSTRUCTION_HOME_IMPROVEMENT__OTHER_TRADES,
    CONSULTANTS_PROFESSIONALS__ACCOUNTANTS_BOOKKEEPERS,
    CONSULTANTS_PROFESSIONALS__COMMUNICATIONS,
    CONSULTANTS_PROFESSIONALS__EXECUTIVE_COACH,
    CONSULTANTS_PROFESSIONALS__HR_RECRUITMENT_STAFFING,
    CONSULTANTS_PROFESSIONALS__IT_TECHNICAL,
    CONSULTANTS_PROFESSIONALS__OTHER,
    CONSULTANTS_PROFESSIONALS__SALES,
    DESIGN_ARCHITECTURE_ENGINEERING,
    FINANCIAL_SERVICES,
    HAIR_SPA_AESTHETICS__HAIR_SALON,
    HAIR_SPA_AESTHETICS__MASSAGE,
    HAIR_SPA_AESTHETICS__NAIL_SKIN_AESTHETICS,
    HAIR_SPA_AESTHETICS__OTHER,
    INSURANCE_AGENCY_BROKER,
    LANDLORD_PROPERTY_MANAGER__LANDLORD,
    LANDLORD_PROPERTY_MANAGER__PROPERTY_MANAGER,
    LAWN_CARE_LANDSCAPING,
    LEGAL_SERVICES,
    LODGING_HOTEL_MOTEL,
    MANUFACTURER_REPRESENTATIVE_AGENT,
    MEDICAL_DENTAL_HEALTH_SERVICE__CHIROPRACTOR,
    MEDICAL_DENTAL_HEALTH_SERVICE__DENTIST,
    MEDICAL_DENTAL_HEALTH_SERVICE__FITNESS,
    MEDICAL_DENTAL_HEALTH_SERVICE__MASSAGE_THERAPIST,
    MEDICAL_DENTAL_HEALTH_SERVICE__MENTAL_HEALTH,
    MEDICAL_DENTAL_HEALTH_SERVICE__NUTRITION,
    MEDICAL_DENTAL_HEALTH_SERVICE__OCCUP_THERAPIST,
    MEDICAL_DENTAL_HEALTH_SERVICE__OTHER,
    MEDICAL_DENTAL_HEALTH_SERVICE__PHYSICAL_THERAPIST,
    NONPROFIT_ASSOCIATIONS_GROUPS__ASSOCIATION,
    NONPROFIT_ASSOCIATIONS_GROUPS__CHARITABLE,
    NONPROFIT_ASSOCIATIONS_GROUPS__CLUB,
    NONPROFIT_ASSOCIATIONS_GROUPS__CONDO,
    NONPROFIT_ASSOCIATIONS_GROUPS__OTHER,
    NONPROFIT_ASSOCIATIONS_GROUPS__PARENT_BOOSTER,
    OTHER__OTHER_PLEASE_SPECIFY,
    PRODUCT_PROVIDER__MANUFACTURER,
    PRODUCT_PROVIDER__MANUFACTURER_AND_VENDOR,
    PRODUCT_PROVIDER__OTHER,
    PRODUCT_PROVIDER__VENDOR,
    REAL_ESTATE_SALES__AGENT,
    REAL_ESTATE_SALES__BROKER,
    REAL_ESTATE_SALES__OTHER,
    RENTAL,
    REPAIR_AND_MAINTENANCE,
    RESTAURANT_CATERER_BAR,
    RETAILERS_AND_RESELLERS__EBAY,
    RETAILERS_AND_RESELLERS__ETSY,
    RETAILERS_AND_RESELLERS__NON_STORE_RETAILER,
    RETAILERS_AND_RESELLERS__OTHER,
    RETAILERS_AND_RESELLERS__STORE_RETAILER,
    SALES_INDEPENDENT_AGENT,
    SERVICE_PROVIDER__CLEANING_JANITORIAL_SERVICES,
    SERVICE_PROVIDER__CUSTOMER_SERVICE_SUPPORT,
    SERVICE_PROVIDER__DOMESTIC_CAREGIVER_EMPLOYER,
    SERVICE_PROVIDER__FITNESS,
    SERVICE_PROVIDER__OFFICE_ADMIN_SUPPORT,
    SERVICE_PROVIDER__OTHER,
    SERVICE_PROVIDER__PERSONAL_CARE,
    SERVICE_PROVIDER__TELEMARKETING,
    SERVICE_PROVIDER__TRANSCRIPTION,
    TRANSPORTATION_TRUCKING_DELIVERY,
    WEB_MEDIA_FREELANCER__DESIGNER,
    WEB_MEDIA_FREELANCER__MARKETING_SOCIAL_MEDIA,
    WEB_MEDIA_FREELANCER__OTHER,
    WEB_MEDIA_FREELANCER__PROGRAMMER,
    WEB_MEDIA_FREELANCER__SEO,
    WEB_MEDIA_FREELANCER__WRITER,
    WHOLESALE_DISTRIBUTION_SALES,
}

/// Area of focus of a business.
#[derive(Debug)]
pub enum BusinessTypeValue {
    ARTISTS_PHOTOGRAPHERS_CREATIVE,
    CONSULTANTS_PROFESSIONALS,
    FINANCE_INSURANCE,
    HAIR_SPA_AESTHETICS,
    MEDICAL_DENTAL_HEALTH_SERVICE,
    NONPROFIT_ASSOCIATIONS_GROUPS,
    OTHER(String),
    PRODUCT_PROVIDER,
    REALESTATE_HOME,
    RETAILERS_AND_RESELLERS,
    SERVICE_PROVIDER,
    WEB_MEDIA_FREELANCER,
}

